emfs/urls.py
from django.urls import path,re_path

from .views import (
	EmfListView,
	EmfDetailSlugView,
	)

app_name = 'emfs'

urlpatterns = [
	path('',EmfListView.as_view(),name='emfs'),
	# path('<slug:emf>',EmfDetailSlugView.as_view(),name='emfsd'), #why this doesn't work ???
    re_path(r'^(?P<slug>[\w-]+)/$',EmfDetailSlugView.as_view(),name='emfsd'),

]

pg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from .views import home_view,blog_view,contact_view,coming_soon, index_view
from billing.views import payment_method_view, payment_method_create_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

from bookings.views import payment_home

urlpatterns = [
	path('',home_view,name='home'),
    path('admin/', admin.site.urls),
    path('contact/',contact_view,name='contact'),
    path('blog/',blog_view,name='blog'),
    
    path('billing/payment-method/',payment_method_view,name='payment-method'),
    path('billing/payment-method/create/',payment_method_create_view,name='payment-method-endpoint'),
    path('payment/',payment_home,name='payment-home'),

    path('accounts/',include('accounts.urls',   namespace='accounts')),

    path('event/',   include('events.urls',     namespace='events')),   
    
    path('emfs/',    include('emfs.urls',       namespace='emfs')),
    
    path('bookings/',include('bookings.urls',   namespace='bookings')),
    
    path('search/',  include('search.urls',     namespace='search')),

    # path('bookings&event=<slug:event>',new_view,name='new'),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),


    path('index', index_view, name = 'index'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cities/models.py
from django.db import models
from django.db.models.signals import pre_save,post_save

from emfs.models import Emf

class City(models.Model):
	city = models.CharField(max_length=150,null=True,blank=True)
	emf  = models.ManyToManyField(Emf)

	class Meta:
		verbose_name='Cities'
		verbose_name_plural = 'Cities'

	def __str__(self):
		return self.city

emfs/models.py
from django.db import models
from django.db.models.signals import pre_save,post_save
from django.utils.text  import slugify

from events.models import Event
# Create your models here.
class EmfManager(models.Manager):
	def get_by_id(self,id):
		qs = self.get_queryset().filter(id=id)
		if qs.count() == 1:
			return qs.first()
		else:
			return None

class Emf(models.Model):
	EVENT_CHOICES 	= (
			('birthday','Birthday'),
			('wedding','Wedding'),
			('dwedding','DWedding'),
			('anniversary','Anniversary'),
			('festive','Festive'),
			('special','Special'),
			('corporate','Corporate'),
		)
	title 		= models.CharField(max_length=60,blank=False,unique=True) #name of the firm
	slug		= models.SlugField(default='emf_slug')
	region 		= models.CharField(max_length=50)				#region of operation 
	email 		= models.EmailField(blank=True,					#email
									unique=True,
									max_length=50)
	phone 		= models.CharField(max_length=12,blank=False,unique=True,) #phone no (to be changed later) 
	events 		= models.ManyToManyField(Event,blank=True)

	objects 	= EmfManager()  #objects = QuerySet()

	def __str__(self):
		return self.title

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return "/emfs/{slug}".format(slug=self.slug)

def emf_pre_save_reciever(sender,instance, *args, **kwargs):
	instance.slug = slugify(instance.title)

pre_save.connect(emf_pre_save_reciever,sender=Emf)

emfs/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.http import Http404

from .models import Emf
from bookings.models import Booking

class EmfListView(ListView):
	template_name = 'emfs/emflist.html' 
	
	def get_context_data(self,*args,**kwargs):
		context = super(EmfListView,self).get_context_data(*args,**kwargs)
		context['emfs'] = Emf.objects.all()
		booking_obj, created = Booking.objects.new_or_get(self.request)
		context['booking_obj'] = booking_obj
		return context

	def get_queryset(self,*args,**kwargs): #overriding the 'get_queryset()' method
		return Emf.objects.all()

class EmfDetailSlugView(DetailView):
	template_name = 'emfs/emfdetail.html'

	def get_context_data(self,*args,**kwargs):
		context = super(EmfDetailSlugView,self).get_context_data(*args,**kwargs)
		booking_obj, created = Booking.objects.new_or_get(self.request)
		context['booking_obj'] = booking_obj
		return context	

	def get_object(self,*args,**kwargs): #overriding the 'get_object()' method
		request 	= self.request
		slug 		= self.kwargs.get('slug')
		instance 	= get_object_or_404(Emf,slug=slug)
		if instance is None:
			raise Http404("Emf doesn't exist")
		return instance

emfs/templates/emfs/emfdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
	<div class="col-12 col-md-6">
		<h4>{{ object.title }}</h4>
	</div>
</div>
<div class="row">
	<div class="col-12 col-md-6">
		Deals in :
		{% for event in object.events.all %}
		<div class="row">
			<div class="col ml-auto mr-auto">
				<a href="{{ event.get_absolute_url }}">{{ event }}</a>
			</div>
		</div>
	{% endfor %}
	</div>
	<div class="col-12 col-md-6">
	{% include 'snippets/update-booking.html' with booking=booking_obj emf=object %}
	</div>
</div>
{% endblock content %}

emfs/templates/emfs/emflist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- delete this file. similar already exist emfs app -->
{% for emf in emfs %}
<div class="card my-4">
  <h5 class="card-header h5"><a href="{{ emf.get_absolute_url }}">{{ emf.title }}</a></h5>
  <div class="card-body">
    <h5 class="card-title">City: {{ emf.city_set.all.first }}</h5> <!-- display all the cities -->
    <div class="row">
    	{% for event in emf.events.all %}
    		<div class="col-lg-3">
    			<a href="{{ event.get_absolute_url }}" ><p class="card-text">{{ event }}</p></a>
    		</div>
    	{% endfor %}
	</div>
	<div class="row">
		<div class="col-2 offset-10">
    		{% include 'snippets/update-booking.html' with booking=booking_obj emf=emf %}
    	</div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}