accounts/urls.py
from django.urls import path,re_path

from .views import (
	login_view,
	RegisterView,
	logout_view,
	)

app_name = 'accounts'

urlpatterns = [
	path('login/',login_view,name='login'),
	path('logout/',logout_view,name='logout'),
	path('register/',RegisterView.as_view(),name='register'),
]

bookings/urls.py
from django.urls import path,re_path

from .views import (
	booking_view,
	booking_home,
	booking_update,
	detail_view,
	checkout,
	checkout_success
	)

app_name = 'bookings'

urlpatterns = [
	path('',booking_view,name='booking'),
	path('event=<slug:event>',booking_view,name='booking'), #make one for city only, and  one for both city & event
	path('home',booking_home,name='home'),
	path('update',booking_update,name='update'),
	path('detals',detail_view,name='details'),
	path('checkout',checkout,name='checkout'),
	path('success',checkout_success,name='success'),
]

pg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from .views import home_view,blog_view,contact_view,coming_soon, index_view
from billing.views import payment_method_view, payment_method_create_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

from bookings.views import payment_home

urlpatterns = [
	path('',home_view,name='home'),
    path('admin/', admin.site.urls),
    path('contact/',contact_view,name='contact'),
    path('blog/',blog_view,name='blog'),
    
    path('billing/payment-method/',payment_method_view,name='payment-method'),
    path('billing/payment-method/create/',payment_method_create_view,name='payment-method-endpoint'),
    path('payment/',payment_home,name='payment-home'),

    path('accounts/',include('accounts.urls',   namespace='accounts')),

    path('event/',   include('events.urls',     namespace='events')),   
    
    path('emfs/',    include('emfs.urls',       namespace='emfs')),
    
    path('bookings/',include('bookings.urls',   namespace='bookings')),
    
    path('search/',  include('search.urls',     namespace='search')),

    # path('bookings&event=<slug:event>',new_view,name='new'),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),


    path('index', index_view, name = 'index'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookings/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save,post_save

from datetime import datetime

from events.models import Event
from cities.models import City
from emfs.models import Emf
from pricing.models import Price

User = settings.AUTH_USER_MODEL


DECOR_CHOICES = (
	('floral','Floral'),
	('sober','Sober'),
	('premium','Premium'),
	('artificial','Artificial'),
	)

class Detail(models.Model):
	decor 				= models.CharField(max_length=40,choices=DECOR_CHOICES,null=True,blank=True)
	photography 		= models.BooleanField(default=True)
	people 				= models.IntegerField()
	DJ_Entertainment	= models.BooleanField(default=False) 


class BookingManager(models.Manager):
	def new_or_get(self,request):
		'''
		A Booking object stays in the session dict as long as the user doesn't log out.
		One session ---> one Booking object
		'''
		booking_id = request.session.get('booking_id',None)
		qs = self.get_queryset().filter(id=booking_id)
		if qs.count() == 1: #already exists
			booking_obj, created = qs.first() , False# print('Booking EXISTS')
			if booking_obj.user is None and request.user.is_authenticated:
				booking_obj.user = request.user
				booking_obj.save()
		else:
			booking_obj,created = Booking.objects.new(user=request.user),True
			request.session['booking_id'] = booking_obj.id
		return booking_obj, created

	def new(self,user=None): #helper method for above method
		user_obj = None
		if user is not None:
			if user.is_authenticated:
				user_obj = user
		return self.model.objects.create(user=user_obj)

class Booking(models.Model):
	user 			= models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
	date_added		= models.DateTimeField(auto_now_add=True,null=True,blank=True)	 
	booking_date 	= models.DateField(null=True,blank=True)
	city 			= models.ForeignKey(City,on_delete=models.CASCADE,null=True,blank=True)
	event 			= models.ForeignKey(Event,on_delete=models.CASCADE,null=True,blank=True)
	emf 			= models.ForeignKey(Emf,on_delete=models.CASCADE,null=True,blank=True)
	amount	 		= models.ForeignKey(Price,on_delete=models.CASCADE,null=True,blank=True) #the emf charge
	details 		= models.ForeignKey(Detail,on_delete=models.CASCADE,null=True,blank=True)

	objects = BookingManager()

	def __str__(self):
		return str(self.id)

def booking_date_pre_save_reciever(sender,instance,*args,**kwargs):
	instance.date_added = datetime.today() #assigns the current date

def pre_save_find_price_reciever(sender,instance,*args,**kwargs):
	'''
	A Booking object is associated with an appropriate Price object before saving.If a relevant Price 
	object exists. Else no changes are made. (an invalid choice was made )
	'''
	if instance.event and instance.emf: #if both have been selected.
		lookups = (Q(event__event__iexact=instance.event)&
					Q(emf__title__iexact=instance.emf)
					)
		qs = Price.objects.filter(lookups) #check if a price object exists or not
		if qs.count() == 1: #we have a Price object
			instance.amount = qs.first() #link to the price object
		else:
			pass
	else:
		pass
pre_save.connect(pre_save_find_price_reciever,sender=Booking)

bookings/forms.py
from django import forms

from .models import Booking, Detail

class DateInput(forms.DateInput):
	input_type = 'date'

class BookingForm(forms.ModelForm):
	class Meta:
		model = Booking
		fields = ('booking_date','city','event')
		widgets = {
			'booking_date': DateInput()
		}
	# def clean_city(self):
	# 	if not self.cleaned_data['city']:
	# 		raise forms.ValidationError('Enter the city for better results.')
	# def clean_event(self):
	# 	if not self.cleaned_data['event']:
	# 		raise forms.ValidationError('Enter the event field for better results.')

class CityForm(forms.ModelForm):
	class Meta:
		model = Booking
		fields = ('city',)

class EventForm(forms.ModelForm):
	class Meta:
		model = Booking
		fields = ('event',)

class DetailForm(forms.ModelForm):
	class Meta:
		model = Detail
		fields = ('decor','photography','people','DJ_Entertainment')

	# def clean_people(self):
	# 	people = self.cleaned_data.get('people')
	# 	if people < 0:
	# 		raise forms.ValidationError("No of People can't be negative")

bookings/views.py
from django.conf import settings
from django.shortcuts import render,redirect,get_object_or_404,render_to_response
from django.http import Http404
from django.contrib import messages
from .models import Booking, Detail
from .forms import BookingForm,CityForm,EventForm, DetailForm
from accounts.forms import LoginForm

from orders.models import Order
from events.models import Event 
from cities.models import City
from emfs.models import Emf
from billing.models import BillingProfile

import stripe
STRIPE_API_KEY = getattr(settings,"STRIPE_API_KEY",'sk_test_jcscEC3iRnTzBfAU7jfVf61o00d4ZW7mqH')
STRIPE_PUB_KEY = getattr(settings,"STRIPE_PUB_KEY",'pk_test_QcT5HsC0UoTP1xRhqbC87uFF009NUrh426')

stripe.api_key = STRIPE_API_KEY

def emf_and_event(booking):
	'''returns True if Emf associated with current Booking instance organises the associated Event'''
	if booking.emf is not None and booking.event is not None:
		return booking.event in booking.emf.events.all()
def emf_and_city(booking):
	'''returns True if Emf associated with current Booking instance operates in the associated City'''
	if booking.city is not None and booking.emf is not None:
		return booking.emf in booking.city.emf.all()

def booking_view(request,*args,**kwargs):
	booking_obj,created = Booking.objects.new_or_get(request)
	context={ 'booking_obj':booking_obj }
	event_slug = kwargs.get('event',None)
	if event_slug is not None: #arrived from HOME page link or the bookings:home
		event = Event.objects.get(slug=event_slug)
		booking_obj.event = event
		booking_obj.save()                     ### move all the save/update logic to booking.models ASAP
		##above save method runs even when the event object is same. ONLY save when its different or None
		data={'city':booking_obj.city,'event':event}
		context['form']     = BookingForm(initial=data)
		#The city may still be there. Consider that too.
		if booking_obj.city is not None:
			context['queryset'] = booking_obj.city.emf.all().filter(events__event__icontains=event.event)
		else: #consider only the event if city is blank
			context['queryset'] = event.emf_set.all().filter()
		return render(request,"bookings/booking.html",context)
	form = BookingForm(request.POST or None) #arrived from the bookings:booking page itself
	date = request.POST.get('booking_date',None)
	if date is not None and len(date):
		booking_obj.booking_date = date
		booking_obj.save()
		##above save method runs even when the date is same. ONLY save when its different or None
	context['form'] = form
	city_id = request.POST.get('city',None) #this is coming from the BookingForm
	eventid = request.POST.get('event',None) #this is coming from the BookingForm
	context['city_set_present'],cityset = False,None
	context['event_set_present'],eventset = False,None
	if city_id is not None and len(city_id):
		city_obj = City.objects.get(id=city_id)
		booking_obj.city = city_obj
		booking_obj.save()
		##above save method runs even when the city object is same. ONLY save when its different or None
		cityset = city_obj.emf.all()
		if cityset.count():
			context['cqs']  = cityset
			context['city_set_present'],context['no_result'] = True,False
	if eventid is not None and len(eventid):
		event = get_object_or_404(Event,id=eventid) #get the event object from event.id
		context['event']  = event
		booking_obj.event = event
		booking_obj.save()
		##above save method runs even when the event object is same. ONLY save when its different or None
		eventset = event.emf_set.all() #emfs that do the event
		if eventset.count():
			context['eqs']  = eventset # event queryset
			context['event_set_present'],context['no_result'] = True,False
	if city_id is not None and eventid is not None: #both are there
		if eventset is not None and cityset is not None:
			# queryset = eventset | cityset
			queryset = cityset.filter(events__event__icontains=event.event)
			if queryset.count(): #both present
				context['queryset'] = queryset.distinct()
				context['both'] = True
				del eventset,cityset #free up some memory
				del context['eqs'],context['cqs']  
	return render(request,"bookings/booking.html",context)

def booking_home(request,*args,**kwargs):
	booking_obj,created = Booking.objects.new_or_get(request) #return a booking object if already exists or creates a new one.	
	form = CityForm(request.POST or None)
	eform = EventForm(request.POST or None)
	context={
		'booking_obj':booking_obj,
		'form':form,
		'eform':eform,
	}
	if booking_obj.event is not None and booking_obj.emf is not None:
		if not emf_and_event(booking_obj):
			context['warning'] = True
	if booking_obj.emf is not None and booking_obj.city is not None:
		if not emf_and_city(booking_obj): #city warning
			context['cwarning'] = True
	return render(request,'bookings/bookinghome.html',context)

def booking_update(request):# del request.session['booking_obj']
	print('POST: ',request.POST)
	booking_obj, created = Booking.objects.new_or_get(request) #get the current BOOKING object, or create a new one.
	if request.method == "POST":
		city_id 	= request.POST.get('city_id')
		event_id 	= request.POST.get('event_id')
		emf_id 		= request.POST.get('emf_id')   
		if city_id is not None and len(city_id):
			city 	= City.objects.get(id=city_id)
			print('getting the city id::',city)
			booking_obj.city = city #add the city
		else:
			city_id = request.POST.get('city') #coming from bookings:update
			if city_id is not None and len(city_id):
				city = City.objects.get(id=city_id) #get the city
				if booking_obj.city == city: #need to remove
					booking_obj.city = None
				else: #need to add
					booking_obj.city = city
		if event_id is not None and len(event_id):
			event 	= Event.objects.get(id=event_id)
			print("getting the Event id::",event)
			booking_obj.event = event #add the event
		else: #coming from bookings:update
			event_id = request.POST.get('event')
			if event_id is not None and len(event_id):
				event = Event.objects.get(id=event_id)
				if booking_obj.event == event: #need to remove
					booking_obj.event = None
				else: #need to add
					booking_obj.event = event
		if emf_id is not None and len(emf_id):
			emf 	= Emf.objects.get(id=emf_id)
			print('getting the Emf id::',emf)
			booking_obj.emf = emf #add the emf
		else: #coming from 'bookings:update'
			emf_id = request.POST.get('emf')
			if emf_id is not None and len(emf_id):
				emf = Emf.objects.get(id=emf_id)
				if booking_obj.emf == emf: #need to remove
					booking_obj.emf = None
				else:
					booking_obj.emf = emf
		booking_obj.save()
	else:
		pass
	return redirect('bookings:home')

def detail_view(request,*args,**kwargs):
	form = DetailForm(request.POST or None)
	if request.method == 'POST' and form.is_valid():
		decor = form.cleaned_data.get('decor',None)
		people = form.cleaned_data.get('people',0)
		photography = form.cleaned_data.get('photography',None)
		dj = form.cleaned_data.get('DJ_Entertainment',None)
		l = [v is not None for (k,v) in form.cleaned_data.items()]
		if all(l): #attach the details to the Booking
			# detail = Detail.objects.create(decor=decor,people=int(people),photography=photography,DJ_Entertainment=dj)
			booking_obj,created = Booking.objects.new_or_get(request)
			booking_obj.details.decor=decor
			booking_obj.details.people=int(people)
			booking_obj.details.photography=photography,
			booking_obj.details.DJ_Entertainment=dj 
			booking_obj.save()
			return redirect('bookings:checkout')# if necessary details have been filled, redirect to 'bookings:checkout'
	context={
		'form':form,
	}
	return render(request,'bookings/details.html',context)

def checkout(request,*args,**kwargs):
	#get the Booking object from the session
	booking_obj,created = Booking.objects.new_or_get(request)
	order_obj = None
	login_form = LoginForm()
	#get the BillingProfile, if the user is  logged in, else a None profile
	billing_profile,created = BillingProfile.objects.new_or_get(request)
	if billing_profile is not None: #we have a billing_profile
		order_obj,created = Order.objects.new_or_get(billing_profile,booking_obj)
	else:
		pass
	if request.method == 'POST': #clicked on 'Proceed to Pay'
		return redirect('payment-home')
		# is_prepared = order_obj.is_done()
		# if is_prepared:
		# 	did_charge,msg = billing_profile.charge(order_obj)
		# 	if did_charge:
		# 		order_obj.mark_paid()	#mark the Order as Paid
		# 		del request.session['booking_id'] #delete the Booking from session
		# 		return redirect('bookings:success') #make this 'billing:success'
		# 	else:
		# 		return redirect('bookings:home')
			# associate the order to user's order history
	context={
		'order_obj':order_obj,
		'billing_profile':billing_profile,
		'login_form':login_form,
	}
	return render(request,'bookings/checkout.html',context)


def payment_home(request,*args,**kwargs):
	billing_profile,created = BillingProfile.objects.new_or_get(request)
	booking_obj,created = Booking.objects.new_or_get(request)
	order_obj,created = Order.objects.new_or_get(billing_profile,booking_obj)
	has_card = billing_profile.has_card
	if request.method == 'POST': #clicked on 'Confirm Payment'
		is_prepared = order_obj.is_done()
		if is_prepared:
			did_charge,msg = billing_profile.charge(order_obj)
			if did_charge:
				order_obj.mark_paid()	#mark the Order as Paid
				del request.session['booking_id'] #delete the Booking from session
				return redirect('bookings:success') #make this 'billing:success'
			else:
				return redirect('bookings:home')
	context={
		'has_card':has_card,
		'order_obj':order_obj,
		'billing_profile':billing_profile,
		'publish_key':STRIPE_PUB_KEY,
	}
	return render(request,'bookings/paymenthome.html',context)

def checkout_success(request,*args,**kwa):
	#attach the order details to user profile
	return render(request,'bookings/success.html',{})

bookings/templates/bookings/booking.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-1 col-md-3 col-lg-8 mr-auto ml-auto" style="min-height: 200px;">
			<form method="POST" action="{% url 'bookings:booking' %}" class="form-control form-group">{% csrf_token %}
				{{ form }}
				<input type="submit" value="Submit">
			</form>
			{% if request.GET.q %}
				{% if found %}
					<p>Results for : <strong>{{ request.GET.q }}</strong> </p>
				{% else %}
					<p>No RESULTS for :<strong> {{ request.GET.q }}</strong></p>
				{% endif %}
			{% endif %}
			{% if no_result %}
				<p> NO RESULTS FOUND. Try Again. </p>
			{% else %}
				{% if both %}
					<p> BOTH </p>
				{% elif event_set_present %}
				    <p> EVENT </p>
				{% elif city_set_present %}
				    <p> CITY </p>
				{% endif %}
				{% if queryset %}
					<div>
					{% include 'snippets/eventemflist2.html' with emfs=queryset booking=booking_obj %}</div>
				{% elif eqs %}
					<p>{{ event }} is organised by </p>
					<div>
					{% include 'snippets/eventemflist2.html' with emfs=eqs booking=booking_obj %}</div>
				{% elif cqs %}
					<div>
					{% include 'snippets/eventemflist2.html' with emfs=cqs booking=booking_obj %}</div>
				{% else %}
					<strong>No Results. Please try again.</strong>
				{% endif %}
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

bookings/templates/bookings/bookinghome.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if warning %}
	<strong><a href="{{ booking_obj.emf.get_absolute_url }}">{{ booking_obj.emf }}</a></strong> don't deal in <strong>{{ booking_obj.event }}</strong>
{% endif %}
{% if cwarning %}
	<p><a href="{{ booking_obj.emf.get_absolute_url }}"><strong>{{ booking_obj.emf }}<a/></strong> don't operate in {{ booking_obj.city }}</p>
{% endif %}
{% if warning or cwarning %}
	<p>Please make another choice.</p>
	<p>Visit their page to know about their services.</p>
{% endif %}
{% if booking_obj.city is None and booking_obj.emf is None %}
	<p><strong>You don't have any bookings to display. Please make one.</strong></p>
	<a class="btn btn-primary" href="{% url 'bookings:booking' %}">Make booking</a>
{% else %}
<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Date</th>
			<th>City</th>
			<th>Event</th>
			<th>EMF</th>
		</tr>
	</thead>
<tbody>
	<tr>
		<td>{{ booking_obj.id }}</td>
		<td>{{ booking_obj.booking_date }}</td>
		<td>
 		{% if booking_obj.city is None %} <!-- display the add city form -->
		 {% include 'snippets/update-city.html' with booking=booking_obj df=True form=form %}
		 {% else %} <!-- show the remove button -->
		 	{{ booking_obj.city }}
		   	{% include 'snippets/update-city.html' with booking=booking_obj city=booking_obj.city %}
		{% endif %}
		</td>
		<td>
		{% if booking_obj.event is None %} <!-- display the add event form -->
		    {% include 'snippets/update-booking-event.html' with booking=booking_obj df=True form=eform %}
		{% else %} <!-- show the remove button -->
		 	<a href="{{ booking_obj.event.get_absolute_url }}">{{ booking_obj.event }}</a>
		   	{% include 'snippets/update-booking-event.html' with booking=booking_obj event=booking_obj.event %}
		{% endif %}
		</td>
		<td>
		{% if booking_obj.emf is not None %}
			<a href="{{ booking_obj.emf.get_absolute_url }}">{{ booking_obj.emf }}</a>
		   {% include 'snippets/update-booking.html' with booking=booking_obj emf=booking_obj.emf %}
		{% else %} <!-- emf is not there -->
			{% if booking_obj.event %}
				<a href="event={{booking_obj.event.slug}}" class="btn btn-primary">ADD AN EMF</a>
			{% else %}
				<a class="btn btn-success" href="{% url 'bookings:booking' %}">Add an EMF</a>
			{% endif %}
		{% endif %}
		</td>
	</tr>
	<tr>
		{% if booking_obj.emf and booking_obj.event and booking_obj.city %}
			<td colspan="3"></td>
			{% if not warning and not cwarning %}
				<td><a class="btn btn-primary" href="{% url 'bookings:details' %}">Add Details</a></td>
			{% endif %}
		{% endif %}
	</tr>
</tbody>
</table>
{% endif %}
{% endblock content %}

bookings/templates/bookings/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="display-4">Checkout view</h3>
{% if not billing_profile %}
	<div class="row">
		<div class="col-md-6 col-sm-12">
			<strong>LOGIN</strong>
			{% include 'snippets/form.html' with form=login_form next=request.build_absolute_uri %}
		</div>
		<div class="col-md-6 col-sm-12">
			<a href="{% url 'accounts:register' %}" class="btn btn-primary">Register</a>
		</div>
	</div>
{% else %}
		<!-- we have a billing profile -->
		{% if order_obj is None or order_obj.booking.event is None and order_obj.booking.emf is None %}
			<strong> No Booking created. Please make a booking first.</strong>
			<a class="btn btn-primary" href="{% url 'bookings:booking' %}">Make a Booking</a>
		{% else %}
		<div class="row">
			<div class="col-6">
				<p><strong>Order ID: </strong>{{ order_obj.order_id }}</p>
				<p><strong>Event: </strong><a href="{{ order_obj.booking.event.get_absolute_url }}">{{ order_obj.booking.event }}</a></p>
				<p><strong>Emf: </strong><a href="{{ order_obj.booking.emf.get_absolute_url }}">{{ order_obj.booking.emf }}</a></p>
				<p><strong>City: </strong>{{ order_obj.booking.city }}</p>
				<p><strong>Booking Date: </strong>{{ order_obj.booking.booking_date }}</p>
				<p><strong>Amount: </strong>{{ order_obj.booking.amount.amount }}</strong></p>
			</div>
			<div class="col-6">
				<strong>Details</strong>
				<p><strong>Decoration: </strong>{{ order_obj.booking.details.decor }}</p>
				<p><strong>Photography: </strong>{% if order_obj.booking.details.photography %}Yes{% else %}No{% endif %}</p>
				<p><strong>No of Guests: </strong>{{ order_obj.booking.details.people }}</p>
				<p><strong>Music & Entertainment: </strong>{% if order_obj.booking.details.DJ_Entertainment %}Yes{% else %}No{% endif %}</p>

				<a class="btn btn-sm btn-outline-primary" href="{% url 'bookings:details' %}">Change details</a>
			</div>
		</div>
			<form method="POST">{% csrf_token %}
				<button type="submit" class="btn btn-success">Proceed to Pay</button>
			</form>
	{% endif %}
{% endif %}
{% endblock content %}

bookings/templates/bookings/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<p> In details view
	<form method="POST">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-success">
	</form>

{% endblock content %}

bookings/templates/bookings/paymenthome.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
	{% if not has_card %}
		<div class='col-10 col-md-6 mx-auto'>
    		<h1>Add Payment Method</h1>
    	<div class='stripe-payment-form' data-token='{{ publish_key }}' data-next-url='{{ request.build_absolute_uri }}' data-btn-title='Add Card'></div>
	</div>
	{% else %} <!-- already has a card saved -->
	<h3 class="display-3">Finalise Order</h3>
		<p><strong>Order ID: </strong>{{ order_obj.order_id }}</p>
		<p><strong>Event: </strong><a href="{{ order_obj.booking.event.get_absolute_url }}">{{ order_obj.booking.event }}</a></p>
		<p><strong>Emf: </strong><a href="{{ order_obj.booking.emf.get_absolute_url }}">{{ order_obj.booking.emf }}</a></p>
		<p><strong>City: </strong>{{ order_obj.booking.city }}</p>
		<p><strong>Booking Date: </strong>{{ order_obj.booking.booking_date }}</p>
		<p><strong>Amount: </strong>{{ order_obj.booking.amount.amount }}</strong>
		<p><strong>Card: </strong>{{ billing_profile.default_card }} (<a href="{{ billing_profile.get_payment_method_url }}?next={{ request.build_absolute_uri }}">Change</a>)</p>
		<form method="POST">{% csrf_token %}
			<button type="submit" class="btn btn-success">Confirm Payment</button>
		</form>
	{% endif %}

{% endblock content %}

bookings/templates/bookings/success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-6 text-center mx-auto">
			<h1 class="display-1">Thank You for your booking! </h1>
		</div>
	</div>
{% endblock content %}