accounts/urls.py
from django.urls import path,re_path

from .views import (
	login_view,
	RegisterView,
	logout_view,
	)

app_name = 'accounts'

urlpatterns = [
	path('login/',login_view,name='login'),
	path('logout/',logout_view,name='logout'),
	path('register/',RegisterView.as_view(),name='register'),
]

bookings/urls.py
from django.urls import path,re_path

from .views import (
	booking_view,
	booking_home,
	booking_update,
	detail_view,
	checkout,
	checkout_success
	)

app_name = 'bookings'

urlpatterns = [
	path('',booking_view,name='booking'),
	path('event=<slug:event>',booking_view,name='booking'), #make one for city only, and  one for both city & event
	path('home',booking_home,name='home'),
	path('update',booking_update,name='update'),
	path('detals',detail_view,name='details'),
	path('checkout',checkout,name='checkout'),
	path('success',checkout_success,name='success'),
]

emfs/urls.py
from django.urls import path,re_path

from .views import (
	EmfListView,
	EmfDetailSlugView,
	)

app_name = 'emfs'

urlpatterns = [
	path('',EmfListView.as_view(),name='emfs'),
	# path('<slug:emf>',EmfDetailSlugView.as_view(),name='emfsd'), #why this doesn't work ???
    re_path(r'^(?P<slug>[\w-]+)/$',EmfDetailSlugView.as_view(),name='emfsd'),

]

pg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from .views import home_view,blog_view,contact_view,coming_soon, index_view
from billing.views import payment_method_view, payment_method_create_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView

from bookings.views import payment_home

urlpatterns = [
	path('',home_view,name='home'),
    path('admin/', admin.site.urls),
    path('contact/',contact_view,name='contact'),
    path('blog/',blog_view,name='blog'),
    
    path('billing/payment-method/',payment_method_view,name='payment-method'),
    path('billing/payment-method/create/',payment_method_create_view,name='payment-method-endpoint'),
    path('payment/',payment_home,name='payment-home'),

    path('accounts/',include('accounts.urls',   namespace='accounts')),

    path('event/',   include('events.urls',     namespace='events')),   
    
    path('emfs/',    include('emfs.urls',       namespace='emfs')),
    
    path('bookings/',include('bookings.urls',   namespace='bookings')),
    
    path('search/',  include('search.urls',     namespace='search')),

    # path('bookings&event=<slug:event>',new_view,name='new'),
    path('settings/email/', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    path('webhooks/mailchimp/', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),


    path('index', index_view, name = 'index'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path

from .views import SearchEmfView

app_name = 'search'
urlpatterns = [
	path('',SearchEmfView.as_view(),name='query'), #rendered for 127.0.0.1:8000/search
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>Planning Gurus</title>
    
    {% include 'base/css.html' %}
  
  </head>
  
  <body>
    
    {% include 'navbar.html' %}
    
    <div class="container">
        {% if messages %}
          <div class="alert alert-success messages">
          {% for message in messages %}
            <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                {{ message }}<br/>
            </span>
            {% endfor %}
        </div>
        {% endif %}
      {% block content %}
      {%  endblock content %}
    </div>
    
    {% include 'base/js.html' %}

  </body>
</html>

templates/blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <p> Blog page </p>
{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<img src='{% static "img/coming-soon.jpg" %}' style="width: 100%; margin-top:0px;">
	<div class="contact">
		<form class="form" method="POST">{% csrf_token %}
			<label>Your name</label><input type="text">
			<label>E-mail</label><input style="width: 300px;" type="text"><br>
			<textarea placeholder="message" class="msg"></textarea>
			<br><input type="submit" value="Submit">
		</form>
	</div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <p>Your one stop for all the events. We have got you covered for the birthdays, kitties, cocktails parties, and all the other kind of parties </p>

	<div class="row">
	{% for eve in events %}
	    <div class="col-lg-6">
	    	{% include 'snippets/card.html' %}
	    </div>
  {% endfor %}
  </div>
{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Complete Bootstrap 4 Website Layout</title>
	<!-- BS CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<!-- JQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<!-- BS JS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<!-- font awesome CDN -->
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href='{% static "css/style.css" %}' rel="stylesheet">
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-brand" href="#"><img src='{% static "img/logo.png" %}'></a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarResponsive">
		<ul class="navbar-nav mr-auto">
			<!-- ml-auto keeps it at right side-->
			<li class="nav-item">
				<a class="nav-link active" href="#">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link " href="#">About</a>
			</li>
			<li class="nav-item">
				<a class="nav-link " href="#">Services</a>
			</li>
			<li class="nav-item">
				<a class="nav-link " href="#">Connect</a>
			</li>
			<li class="nav-item">
		       <form class="form-inline my-2 ml-2" action="{% url 'search:query' %}">
		         <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
		         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		       </form>
		     </li>
		</ul>
	</div>
</div>
</nav>

<!--- Image Slider -->
<div id="slides" class="carousel slide" data-ride="carousel">
	<ul class="carousel-indicators">
		<li data-target="#slides" data-slide-to="0" class="active"></li>
		<li data-target="#slides" data-slide-to="1"></li>
		<li data-target="#slides" data-slide-to="2"></li>
	</ul>
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src='{% static "img/slideshow/1.jpg" %}'>
			<div class="carousel-caption">
				<h1 class="display-2">Planning Gurus</h1>
				<h3>Events Simplified</h3>
				<button type="button" class="btn btn-outline-light btn-lg">VIEW DEMO</button>
				<button type="button" class="btn btn-primary btn-lg">GET STARTED</button>
			</div>
		</div>
		<div class="carousel-item">
			<img src='{% static "img/slideshow/2.jpg" %}'>
		</div>
		<div class="carousel-item">	
			<img src='{% static "img/slideshow/4.jpg" %}'>
		</div>
	</div>
</div>

<!--- Jumbotron -->
<div class="container-fluid">
	<div class="row jumbotron">
		<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10">
			<p class="lead">An online service that allows individuals and organisations to search,analyse & book
				every aspect of event management.
			</p>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 col-xl-2">
			<a href="#"><button type="button" class="btn btn-outline-secondary btn-lg">Register</button></a>
		</div>
	</div>
</div>
<!--- Welcome Section -->
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h1 class="display-4">Plan with ease.</h1>
		</div>
		<hr>
		<div class="col-12">
			<p class="lead">Welcome to Planning Gurus. We do all the heavy work when it comes to planning &
			organising events.So that you can sit back & relax.</p>
		</div>
	</div>
</div>
<!--- Three Column Section -->

<div class="container-fluid padding">
	<div class="row text-center padding">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<i class="fas fa-code"></i>
			<h3>HTML5</h3>
			<p class="lead">Built with the latest version of HTML, HTML 5</p>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<i class="fas fa-bold"></i>
			<h3>BOOTSTRAP 4</h3>
			<p class="lead">Built with the latest version of Bootstrap, Bootstrap 4</p>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-4">
			<i class="fab fa-css3"></i>
			<h3>CSS3</h3>
			<p class="lead">Built with the latest version of CSS, CSS 3</p>
		</div>
	</div>
	<hr class="my-4">
</div>

<!--- Two Column Section -->

<div class="container-fluid padding">
	<div class="row padding">
		<div class="col-lg-6">
			<h2>If you build it...</h2>
			<p>The columns will automatically stack on top of each other when the screen is 
			less than 576px wide</p>
			<p>Resize the browser window to see the effect. Responsidve Web design has become more 
			important as the amount of mobile traffic now accounts for more than half of the total
			internet traffic.</p>
			<p>It can also display the web page differently depending on the screen size or viewing device.</p>
			<a href="#" class="btn btn-primary">Learn More</a>
 		</div>
 		<div class="col-lg-6">
 			<img src='{% static "img/desk.png" %}' class="img-fluid">
 		</div>
	</div>
</div>	

<hr class="my-4">

<!--- Fixed background -->

<figure>
	<div class="fixed-wrap">
		<div id="fixed">
		</div>
	</div>
</figure>

<!--- Emoji Section -->

<button class="fun" data-toggle="collapse" data-target="#emoji">Click for fun</button>
<div id="emoji" class="collapse">
	<div class="container-fluid padding">
		<div class="row text-center">
			<div class="col-sm-6 col-md-3">
				<img class="gif" src='{% static "gif/panda.gif" %}'>
			</div>
			<div class="col-sm-6 col-md-3">
				<img class="gif" src='{% static "gif/poo.gif" %}'>
			</div>
			<div class="col-sm-6 col-md-3">
				<img class="gif" src='{% static "gif/unicorn.gif" %}'>
			</div>
			<div class="col-sm-6 col-md-3">
				<img class="gif" src='{% static "gif/chicken.gif" %}'>
			</div>
		</div>
	</div>
</div>
  
<!--- Meet the team -->
<div class="container-fluid padding">
	<div class="row welcome text-center">
		<div class="col-12">
			<h1 class="display-4">Meet the Team</h1>
		</div>
		<hr>
	</div>
</div>

<!--- Cards -->

<div class="container-fluid padding">
	<div class="row padding">
		<div class="col-md-4">
			<div class="card">
				<img class="card-img top" src='{% static "img/wed3.jpg" %}'>
				<div class="card-body">
					<h4 class="card-title">Wedding</h4>
					<p class="card-text">John is an Internet entrepreneur with almost 20 years of experience.
					</p>
					<a href="#" class="btn btn-outline-secondary">See Profile</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card">
				<img class="card-img top" src='{% static "img/festive.jpg" %}'>
				<div class="card-body">
					<h4 class="card-title">Festive</h4>
					<p class="card-text">John is an Internet entrepreneur with almost 20 years of experience.
					</p>
					<a href="#" class="btn btn-outline-secondary">See Profile</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card">
				<img class="card-img top" src='{% static "img/team3.png" %}'>
				<div class="card-body">
					<h4 class="card-title">John Doe</h4>
					<p class="card-text">John is an Internet entrepreneur with almost 20 years of experience.
					</p>
					<a href="#" class="btn btn-outline-secondary">See Profile</a>
				</div>
			</div>
		</div>
	</div>
</div>

<!--- Two Column Section -->

<div class="container-fluid padding">
	<div class="row padding">
		<div class="col-lg-6">
			<h2>Our Philosophy</h2>
			<p>We know that greatness in a disruptive era requires bold ambition,curious talent
			and a culture that believes we're smarter together.</p>
			<p>We approach each challenge holistically, with best-in-class expertise in data,creativity,
			media,technology,search, social and more.We call this Alchemy. It has the power to build our clients' brands and transform their business. And while it may seem like magic,we've got it down
			to a science.</p>
			<br>
 		</div>
 		<div class="col-lg-6">
 			<img src='{% static "img/bootstrap2.png" %}' class="img-fluid">
 		</div>
	</div>
	<hr class="my-4">
</div>

<!--- Connect -->

<div class="container-fluid padding">
	<div class="row text-center padding">
		<div class="col-12">
			<center><h2>Connect</h2></center>
		</div>
		<div class="col-12 social padding">
			<a href="#"><i class="fab fa-facebook"></i></a>
			<a href="#"><i class="fab fa-twitter"></i></a>
			<a href="#"><i class="fab fa-google-plus-g"></i></a>
			<a href="#"><i class="fab fa-youtube"></i></a>
		</div>
	</div>
</div>

<!--- Footer -->

<footer>
	<div class="container-fluid padding">
		<div class="row text-center">
			<div class="col-md-4">
				<img src="{% static 'img/w3newbie.png' %}">
				<hr class="light">
				<p>555-555-555</p>
				<p>email@pg.com</p>
				<p>100,Krishna Nagar</p>
				<p>Mathura,UP</p>
			</div>
			<div class="col-md-4">
				<hr class="light">
				<h5>Our hours</h5>
				<hr class="light">
				<p>Monday: 9am-5am</p>
				<p>Saturday: 10am-4pm</p>
				<p>Sunday: closed</p>
			</div>
			<div class="col-md-4">
				<hr class="light">
				<h5>Service Area</h5>
				<hr class="light">
				<p>City, State, 0000</p>
				<p>City, State, 0000</p>
				<p>City, State, 0000</p>
				<p>City, State, 0000</p>
			</div>
			<div class="col-12">
				<hr class="light-100">
				<h5>&copy;<a href="#">planningurus.com</a></h5>
			</div>
		</div>
	</div>
</footer>

</body>
</html>
 <!--- Check out my Bootstrap 4 Courses! -->
 <!-- <div style="float:left; max-width: 46%; margin: 2%; padding: 10px; border: 10px solid #666;">
  <a href="http://bit.ly/advanced-bootstrap-course" target="_blank" style="text-decoration: none;"><h1 style="text-align: center; font-size: 1.2rem; font-family: sans-serif; padding: 1rem; color: #1ba892; letter-spacing: .1rem;">Learn Bootstrap 4 By Creating An Advanced Bootstrap Theme</h1></a>
  <a href="http://bit.ly/advanced-bootstrap-course " target="_blank"><img style="max-width: 100%;"src="https://www.w3newbie.com/wp-content/uploads/nuno-udemy-thumbnail.png"></a>
  <a href="http://bit.ly/advanced-bootstrap-course" target="_blank" style="text-decoration: none;"><h1 style="text-align: center; font-size: 1.5rem; font-family: sans-serif; padding: 2rem; color: #1ba892; letter-spacing: .1rem;">{  94% OFF Coupon Link:  "NUNO93"  }</h1></a>
</div>
 -->
<!-- <div style="float:right; max-width: 46%; margin: 2%; padding: 10px; border: 10px solid #666;">
  <a href="http://bit.ly/NESTCOURSE93" target="_blank" style="text-decoration: none;"><h1 style="text-align: center; font-size: 1.3rem; font-family: sans-serif; padding: 1rem; color: #674FE3; letter-spacing: .1rem;">Bootstrap 4 Website Build From Scratch In 3 Hours</h1></a>
  <a href="http://bit.ly/NESTCOURSE93" target="_blank"><img style="max-width: 100%;"src="https://www.w3newbie.com/wp-content/uploads/bootstrap-theme-couse.png"></a>
  <a href="http://bit.ly/NESTCOURSE93" target="_blank" style="text-decoration: none;"><h1 style="text-align: center; font-size: 1.5rem; font-family: sans-serif; padding: 2rem; color: #674FE3; letter-spacing: .1rem;">{  93% OFF Coupon Link:  "NEST93"  }</h1></a>
</div> -->
<!--- Check out my Bootstrap 4 Courses! -->

templates/index1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- FONT AWESOME CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>Planning Gurus</title>
  </head>
  <body>
  	
  	<form method="POST" action="#" class="form">
  		<textarea ></textarea>
  		<input type="text"/>
  		<textarea ></textarea>
  		<button type="submit">Submit</button>
  	</form>

    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
   
    <!-- <script type="text/javascript">
    	// $(document).ready(function(){

    		// var form = $('.form')
    		// form.submit(function(event){
    			// event.preventDefault()
    			// content = $(this).find('textarea')
    			// console.log('Content:: ',content.val())
    		// })
    	// 	var arr = [1,2,'arvind',false]
    	// 	console.log('arr',arr)
    	// 	$.each(arr,function(index,ele){
    	// 		console.log('index:',index,'element:',ele)
    	// 	})
    		// var heading = $("#h")
    		// console.log('working')
    		// console.log(heading[0].innerHTML)
    		// console.log('printed?')
    		// heading.click(function(event){
    		// 	var $this = $(this)
    		// 	console.log($this[0].innerHTML)
    		// 	console.log(event)
    		// 	window.location.href = 'wwww.google.com'

    		// })
    		// var link = $('#link')
    		// link.click(function(event){
    		// 	var $this = $(this)
    		// 	console.log('Link text',$this[0].innerHTML)
    		// 	var href = $this.attr('href')
    		// 	console.log('Link href',href)
    		// 	event.preventDefault()
    		// 	alert(href)
    		// 	console.log('prevented')
    	
    		// })
    	})
    </script>
    <script type="text/javascript">
    	$(document).ready(function(){
    		var heading = $("#h")
    		console.log('working')
    		console.log(heading.length)
    		setTimeout(function(){
    			// $('body').css("background-color","seagreen")
    			$('#h').css('color','red')
    			$('h1:nth-child(2)').text('Hello arvind')
    		},2000)
    			
    		// alert("hello")
    	})
    </script> -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/navbar.html
{% url 'home' as home_url %}
{% url 'blog' as blog_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'bookings:home' as booking_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <i class="fab fa-product-hunt fa-2x"></i>
  <a class="navbar-brand" href="{% url 'home' %}">Planning Gurus</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link {% if request.path == home_url %}active{% endif %}"href="{% url 'home' %}"><i class="fas fa-home"></i><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == blog_url %}active{% endif %}" href="{% url 'blog' %}">Blog</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Book
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'bookings:booking' %}">Make Booking</a>
          <a class="dropdown-item {% if request.path == booking_url %}active{% endif %}" href="{% url 'bookings:home' %}">Bookings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'emfs:emfs' %}">EMFs</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == booking_url %}active{% endif %}" href="{% url 'bookings:home' %}"><i class="fas fa-id-card-alt"></i></a>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
       <form class="form-inline my-2 ml-2" action="{% url 'search:query' %}">
         <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
         <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
       </form>
     </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link">Welcome {{ request.user.name }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == login_url %}active{% endif %}" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == register_url %}active{% endif %}" href="{% url 'accounts:register' %}"><i class="fas fa-user-plus"></i></a>
        </li>
      {% endif %}
  </ul>
  </div>
</nav>

templates/social_footer.html
<!-- Footer -->
<footer class="page-footer font-small mdb-color pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">

      <!-- Footer links -->
      <div class="row text-center text-md-left mt-3 pb-3">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Company name</h6>
          <p>Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur
            adipisicing elit.</p>
        </div>
        <!-- Grid column -->

        <hr class="w-100 clearfix d-md-none">

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Products</h6>
          <p>
            <a href="#!">MDBootstrap</a>
          </p>
          <p>
            <a href="#!">MDWordPress</a>
          </p>
          <p>
            <a href="#!">BrandFlow</a>
          </p>
          <p>
            <a href="#!">Bootstrap Angular</a>
          </p>
        </div>
        <!-- Grid column -->

        <hr class="w-100 clearfix d-md-none">

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
          <p>
            <a href="#!">Your Account</a>
          </p>
          <p>
            <a href="#!">Become an Affiliate</a>
          </p>
          <p>
            <a href="#!">Shipping Rates</a>
          </p>
          <p>
            <a href="#!">Help</a>
          </p>
        </div>

        <!-- Grid column -->
        <hr class="w-100 clearfix d-md-none">

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p>
            <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
          <p>
            <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
          <p>
            <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->

      </div>
      <!-- Footer links -->

      <hr>

      <!-- Grid row -->
      <div class="row d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-7 col-lg-8">

          <!--Copyright-->
          <p class="text-center text-md-left">© 2019:
            <a href="#">
              <strong> Planning Gurus</strong>
            </a>
          </p>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-5 col-lg-4 ml-lg-0">

          <!-- Social buttons -->
          <div class="text-center text-md-right">
            <ul class="list-unstyled list-inline">
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-google-plus-g"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a class="btn-floating btn-sm rgba-white-slight mx-1">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
            </ul>
          </div>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

  </footer>
  <!-- Footer -->